[package]
name = "sandybox1"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
rand = "0.8"
serde_json = "1.0"
base64 = "0.21"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
